## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")

In [4]:
city_data_df.head()

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Current Description,Wind Speed
0,0,Sinnamary,GF,5.3833,-52.9500,77.22,85,38,scattered clouds,9.06
1,1,Atuona,PF,-9.8000,-139.0333,77.18,75,25,scattered clouds,19.86
2,2,Manokwari,ID,-0.8667,134.0833,83.05,65,89,overcast clouds,4.70
3,3,Longyearbyen,SJ,78.2186,15.6401,48.04,93,75,broken clouds,8.05
4,4,Avarua,CK,-21.2078,-159.7750,71.65,78,75,broken clouds,12.66

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 

min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,Unnamed: 0,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Current Description,Wind Speed
0,0,Sinnamary,GF,5.3833,-52.9500,77.22,85,38,scattered clouds,9.06
1,1,Atuona,PF,-9.8000,-139.0333,77.18,75,25,scattered clouds,19.86
2,2,Manokwari,ID,-0.8667,134.0833,83.05,65,89,overcast clouds,4.70
6,6,Hilo,US,19.7297,-155.0900,80.28,84,100,overcast clouds,6.91
9,9,Georgetown,MY,5.4112,100.3354,87.73,79,20,few clouds,9.22
11,11,Sulangan,PH,11.1373,123.7228,78.60,84,100,light rain,7.76
14,14,Inta,RU,66.0317,60.1659,77.50,53,0,clear sky,16.37
17,17,Meulaboh,ID,4.1363,96.1285,84.52,66,81,broken clouds,4.61
18,18,Vaini,TO,-21.2000,-175.2000,77.16,100,40,scattered clouds,5.75
20,20,Suluktu,KG,39.9337,69.5700,80.08,25,0,clear sky,7.02

In [7]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

Unnamed: 0             443
City                   443
Country                443
Lat                    443
Lng                    443
Max Temp               443
Humidity               443
Cloudiness             443
Current Description    443
Wind Speed             443
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#there are no empty rows

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Sinnamary,GF,77.22,scattered clouds,5.3833,-52.9500,
1,Atuona,PF,77.18,scattered clouds,-9.8000,-139.0333,
2,Manokwari,ID,83.05,overcast clouds,-0.8667,134.0833,
6,Hilo,US,80.28,overcast clouds,19.7297,-155.0900,
9,Georgetown,MY,87.73,few clouds,5.4112,100.3354,
11,Sulangan,PH,78.60,light rain,11.1373,123.7228,
14,Inta,RU,77.50,clear sky,66.0317,60.1659,
17,Meulaboh,ID,84.52,broken clouds,4.1363,96.1285,
18,Vaini,TO,77.16,scattered clouds,-21.2000,-175.2000,
20,Suluktu,KG,80.08,clear sky,39.9337,69.5700,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
import pprint
for index, row in hotel_df.iterrows():
        
    # 6c. Get latitude and longitude from DataFrame     
        lat = row["Lat"]
        lng = row["Lng"]
        params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # 6e. Make request and retrieve the JSON data from the search. 
        hotels = requests.get(base_url, params=params).json()
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
        pprint.pprint(hotels)
        break

{'html_attributions': [],
 'results': [{'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': 5.375086899999999,
                                        'lng': -52.95165650000001},
                           'viewport': {'northeast': {'lat': 5.376353830291502,
                                                      'lng': -52.9504790197085},
                                        'southwest': {'lat': 5.373655869708498,
                                                      'lng': -52.9531769802915}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'icon_background_color': '#909CE1',
              'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
              'name': 'ALETHEIA Appartement Sinnamary',
              'opening_hours': {'open_now': True},
              'photos': [{'height': 600,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/108631877015780232197">dalmo '
                                                'pereira</a>'],
                          'photo_reference': 'AeJbb3e_G8D6cgmlZm8-j3401x_RkYpFxge8sg7JhVs0NtO1wLkPR-3pBJBP511UmaOlQXC-ENVupki8ZiwnSpI7sp2GUEhTnd7ieNALwOypHjQZDJ_0vW8_h8y6JJOFZ3FlKbmrmdaPfXjeYO-ej3vy8zlFpGVFd_oljfSzbUaPvXCfxw8W',
                          'width': 800}],
              'place_id': 'ChIJI8U4MnIWDo0Ru8IqGvZmgr8',
              'reference': 'ChIJI8U4MnIWDo0Ru8IqGvZmgr8',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'vicinity': '92GX+28P'},
             {'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': 5.362393399999999,
                                        'lng': -52.9624634},
                           'viewport': {'northeast': {'lat': 5.363742380291501,
                                                      'lng': -52.9611144197085},
                                        'southwest': {'lat': 5.361044419708497,
                                                      'lng': -52.9638123802915}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'icon_background_color': '#909CE1',
              'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
              'name': "L'oiseau de Paradis",
              'photos': [{'height': 3456,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/113905032882679647005">jeanjacques '
                                                'voillot</a>'],
                          'photo_reference': 'AeJbb3eKL1B9RuuhzxUkHmrjxSbaGCJdIyRN_OPqHObm2Gv1WMu3bY8qSd66amx-Adi_2Cmr1Pg-VCbofbvp7yxYVaCWak0EyX-NBxVMjJvfyXBtIkxnOt4c1Zt68QS1YdHKu0XPomM-wt1I5k0jHzm-erhxMUSJvNfN3bFsRvTcs9pXC82P',
                          'width': 4608}],
              'place_id': 'ChIJq-GI0JEWDo0R5_VFQYOeSyc',
              'plus_code': {'compound_code': '926Q+X2 Sinnamary, French Guiana',
                            'global_code': '68Q9926Q+X2'},
              'rating': 4.6,
              'reference': 'ChIJq-GI0JEWDo0R5_VFQYOeSyc',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 66,
              'vicinity': 'RN1 -PK111 Degrad Fontine 97315 Sinnamary'},
             {'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': 5.3755973, 'lng': -52.9533934},
                           'viewport': {'northeast': {'lat': 5.377148530291503,
                                                      'lng': -52.95160206970851},
                                        'southwest': {'lat': 5.374450569708499,
                                                      'lng': -52.95430003029151}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'icon_background_color': '#909CE1',
              'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
              'name': 'Boutant',
              'photos': [{'height': 2268,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/106045090446199439432">Zivojin '
                                                'RADULOVIC</a>'],
                          'photo_reference': 'AeJbb3cUTetcIGRgoRlROzvKwfNu3YPIFiUexLuG_XOAgN4U7iko5NfIxqW2zqGUy_CCVGwJetM8hDJCvguWZNL4pfTS-QOnoyEPjW-Za3DOPviLeOI6hErqpDaOvwWqVn0sZLlh4GML-Al5VxSWv4J24FAzwHWJk9p4qx56VOFOno_n7xvM',
                          'width': 4032}],
              'place_id': 'ChIJEwrd6nMWDo0RorkBaY7tqBU',
              'rating': 3.5,
              'reference': 'ChIJEwrd6nMWDo0RorkBaY7tqBU',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 4,
              'vicinity': '92GW+6JQ, N 2001, Sinnamary'},
             {'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': 5.371645,
                                        'lng': -52.95225010000001},
                           'viewport': {'northeast': {'lat': 5.373068980291502,
                                                      'lng': -52.95090486970851},
                                        'southwest': {'lat': 5.370371019708498,
                                                      'lng': -52.9536028302915}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'icon_background_color': '#909CE1',
              'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
              'name': 'Ilha hotel',
              'place_id': 'ChIJmbQwCh0YDo0R5aVoFT5n_i8',
              'reference': 'ChIJmbQwCh0YDo0R5aVoFT5n_i8',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'vicinity': '92CX+M35'},
             {'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': 5.3618802, 'lng': -52.9481367},
                           'viewport': {'northeast': {'lat': 5.363162130291502,
                                                      'lng': -52.9465877197085},
                                        'southwest': {'lat': 5.360464169708498,
                                                      'lng': -52.9492856802915}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'icon_background_color': '#909CE1',
              'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
              'name': 'Hotel Du Fleuve',
              'opening_hours': {'open_now': True},
              'photos': [{'height': 1844,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/101296542436271396947">Muriel '
                                                'Jedynak</a>'],
                          'photo_reference': 'AeJbb3ezAiq7K2hqP1nnDmh81UaI8lu4DGfMw00ZxYO3fFoyfGzZuxP7C3uY2e45cVNDHQjvyZuPHPu-lVfePiUhI6eup68CoFzfF7a983k0T5650HIn60TS1vpY-6x7kW4H2nP_qYOYQwJKhLOzHSxBC0S58GSynF5nU74dp6B9Q-YiLQUR',
                          'width': 4000}],
              'place_id': 'ChIJfzT_6P8XDo0RmT76aV5_bP0',
              'rating': 3.4,
              'reference': 'ChIJfzT_6P8XDo0RmT76aV5_bP0',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 49,
              'vicinity': '9362+QP5, Sinnamary'},
             {'business_status': 'OPERATIONAL',
              'geometry': {'location': {'lat': 5.3514856,
                                        'lng': -52.94547660000001},
                           'viewport': {'northeast': {'lat': 5.352838380291502,
                                                      'lng': -52.9441177197085},
                                        'southwest': {'lat': 5.350140419708498,
                                                      'lng': -52.9468156802915}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
              'icon_background_color': '#909CE1',
              'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
              'name': 'L’oiseau de paradis',
              'place_id': 'ChIJSaDgTtIXDo0RgCbAfRu_Yzk',
              'rating': 5,
              'reference': 'ChIJSaDgTtIXDo0RgCbAfRu_Yzk',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 1,
              'vicinity': '9323+HRR, Unnamed Road'}],
 'status': 'OK'}

In [11]:
# 7. Drop the rows where there is no Hotel Name.

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
        # Get the latitude and longitude.
        lat = row["Lat"]
        lng = row["Lng"]

        # Add the latitude and longitude to location key for the params dictionary.
        params["location"] = f"{lat},{lng}"

        # Use the search term: "lodging" and our latitude and longitude.
        base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
        # Make request and get the JSON data from the search.
        hotels = requests.get(base_url, params=params).json()

            # Grab the first hotel from the results and store the name.
        try:
            hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        except (IndexError):
            print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [12]:
clean_hotel_df = hotel_df[hotel_df["Hotel Name"]!= '']
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Sinnamary,GF,77.22,scattered clouds,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
1,Atuona,PF,77.18,scattered clouds,-9.8000,-139.0333,Villa Enata
2,Manokwari,ID,83.05,overcast clouds,-0.8667,134.0833,Swiss Belhotel Manokwari
6,Hilo,US,80.28,overcast clouds,19.7297,-155.0900,Hilo Hawaiian Hotel
9,Georgetown,MY,87.73,few clouds,5.4112,100.3354,Cititel Penang
11,Sulangan,PH,78.60,light rain,11.1373,123.7228,Maia's Beach Resort
14,Inta,RU,77.50,clear sky,66.0317,60.1659,Apartments in Inta city
17,Meulaboh,ID,84.52,broken clouds,4.1363,96.1285,Kost Pria
18,Vaini,TO,77.16,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
22,Dingle,PH,75.81,overcast clouds,10.9995,122.6711,SEGAYA PROPERTY

In [13]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [14]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """

<dl>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""


# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [16]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure()
fig.add_layer(marker_layer)


# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))